from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products_views, name='home'),


    
    path('shop/', views.product_list, name='product_list'),
    path('search/', views.search_products, name='search_products'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
    path('get-variant-details/', views.get_variant_details, name='get_variant_details'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('eid-collection/', views.eid_collection, name='eid_collection'),
    path('new-arrivals/', views.new_arrivals, name='new_arrivals'),
    # Women's product URLs
    path('category/men/', views.men_category, name='men'),
    path('men/casual-shirts/', views.men_casual_shirts, name='men_casual_shirts'),
    path('men/formal-shirts/', views.men_formal_shirts, name='men_formal_shirts'),
    path('men/polo-shirts/', views.men_polo_shirts, name='men_polo_shirts'),
    path('men/t-shirts/', views.men_t_shirts, name='men_t_shirts'),
    path('men/chinos/', views.men_chinos, name='men_chinos'),
    path('men/formal-pants/', views.men_formal_pants, name='men_formal_pants'),
    path('men/formal-jeans/', views.men_jeans, name='men_jeans'),
    path('men/casual-shorts/', views.men_shorts, name='men_shorts'),
    path('men/panjabi/', views.men_panjabi, name='men_panjabi'),
    path('men/kabli/', views.men_kabli, name='men_kabli'),
    path('men/fatua/', views.men_fatua, name='men_fatua'),
    path('men/waistcoats/', views.men_waistcoats, name='men_waistcoats'),
    path('men/pajamas/', views.men_pajamas, name='men_pajamas'),

    # Women's product URLs
    path('category/women/', views.women_category, name='women'),
    path('women/tops/', views.women_tops, name='women_tops'),
    path('women/dresses/', views.women_dresses, name='women_dresses'),
    path('women/jeans/', views.women_jeans, name='women_jeans'),
    path('women/skirts/', views.women_skirts, name='women_skirts'),
    path('women/blouses/', views.women_blouses, name='women_blouses'),
    path('women/jumpsuits/', views.women_jumpsuits, name='women_jumpsuits'),
    path('women/activewear/', views.women_activewear, name='women_activewear'),
    path('women/outerwear/', views.women_outerwear, name='women_outerwear'),
    path('women/lingerie/', views.women_lingerie, name='women_lingerie'),
    path('women/shoes/', views.women_shoes, name='women_shoes'),
    path('women/accessories/', views.women_accessories, name='women_accessories'),
    path('women/mystika/', views.women_mystika, name='women_mystika'),
    path('women/bling/', views.women_bling, name='women_bling'),
    path('women/t-shirts/', views.women_t_shirts, name='women_t_shirts'),
    path('women/pants/', views.women_pants, name='women_pants'),
    path('women/tanks/', views.women_tanks, name='women_tanks'),
    path('women/ethnic-kurtis/', views.women_ethnic_kurtis, name='women_ethnic_kurtis'),
    path('women/ethnic-sets/', views.women_ethnic_sets, name='women_ethnic_sets'),
    path('women/lawn-kurtis/', views.women_lawn_kurtis, name='women_lawn_kurtis'),
    path('women/two-piece/', views.women_two_piece, name='women_two_piece'),
    path('women/three-piece/', views.women_three_piece, name='women_three_piece'),
    path('women/ethnic-pants/', views.women_ethnic_pants, name='women_ethnic_pants'),
    path('women/sarees/', views.women_sarees, name='women_sarees'),
    path('women/totes/', views.women_totes, name='women_totes'),

    # Kids product URLs
    path('category/kids/', views.kids_category, name='kids'),
    path('boys/panjabi/', views.boys_panjabi, name='boys_panjabi'),
    path('boys/kabli/', views.boys_kabli, name='boys_kabli'),
    path('boys/shirts/', views.boys_shirts, name='boys_shirts'),
    path('boys/polos/', views.boys_polos, name='boys_polos'),
    path('boys/tshirts/', views.boys_tshirts, name='boys_tshirts'),
    path('boys/bottoms/', views.boys_bottoms, name='boys_bottoms'),
    path('boys/shorts/', views.boys_shorts, name='boys_shorts'),
    path('boys/prince/', views.boys_prince, name='boys_prince'),
    path('girls/ethnic-tops/', views.girls_ethnic_tops, name='girls_ethnic_tops'),
    path('girls/lawn/', views.girls_lawn, name='girls_lawn'),
    path('girls/tops/', views.girls_tops, name='girls_tops'),
    path('girls/bottom/', views.girls_bottom, name='girls_bottom'),
    path('girls/dresses/', views.girls_dresses, name='girls_dresses'),
    path('girls/princess/', views.girls_princess, name='girls_princess'),
    path('junior-boys/panjabi/', views.junior_boys_panjabi, name='junior_boys_panjabi'),
    path('junior-boys/kabli/', views.junior_boys_kabli, name='junior_boys_kabli'),
    path('junior-boys/top/', views.junior_boys_top, name='junior_boys_top'),
    path('junior-boys/bottom/', views.junior_boys_bottom, name='junior_boys_bottom'),
    path('junior-girls/ethnic/', views.junior_girls_ethnic, name='junior_girls_ethnic'),
    path('junior-girls/lawn/', views.junior_girls_lawn, name='junior_girls_lawn'),
    path('junior-girls/top/', views.junior_girls_top, name='junior_girls_top'),
    path('junior-girls/bottom/', views.junior_girls_bottom, name='junior_girls_bottom'),
]
